<?php
/**
 * Cláusulas normativas ISO para evaluación de auditoría.
 * Basado en ISO 9001:2015, ISO 14001:2015, ISO/IEC 27001:2022
 */
return [

    /* ─── ISO 9001:2015 ─────────────────────────────────────────────── */
    'ISO 9001' => [
        ['codigo' => '4.1',   'titulo' => 'Comprensión de la organización y su contexto'],
        ['codigo' => '4.2',   'titulo' => 'Comprensión de las necesidades y expectativas de las partes interesadas'],
        ['codigo' => '4.3',   'titulo' => 'Determinación del alcance del SGC'],
        ['codigo' => '4.4',   'titulo' => 'Sistema de gestión de la calidad y sus procesos'],
        ['codigo' => '5.1',   'titulo' => 'Liderazgo y compromiso'],
        ['codigo' => '5.2',   'titulo' => 'Política de calidad'],
        ['codigo' => '5.3',   'titulo' => 'Roles, responsabilidades y autoridades en la organización'],
        ['codigo' => '6.1',   'titulo' => 'Acciones para abordar riesgos y oportunidades'],
        ['codigo' => '6.2',   'titulo' => 'Objetivos de la calidad y planificación para lograrlos'],
        ['codigo' => '6.3',   'titulo' => 'Planificación de los cambios'],
        ['codigo' => '7.1',   'titulo' => 'Recursos'],
        ['codigo' => '7.2',   'titulo' => 'Competencia'],
        ['codigo' => '7.3',   'titulo' => 'Toma de conciencia'],
        ['codigo' => '7.4',   'titulo' => 'Comunicación'],
        ['codigo' => '7.5',   'titulo' => 'Información documentada'],
        ['codigo' => '8.1',   'titulo' => 'Planificación y control operacional'],
        ['codigo' => '8.2',   'titulo' => 'Requisitos para los productos y servicios'],
        ['codigo' => '8.3',   'titulo' => 'Diseño y desarrollo de los productos y servicios'],
        ['codigo' => '8.4',   'titulo' => 'Control de los procesos, productos y servicios suministrados externamente'],
        ['codigo' => '8.5',   'titulo' => 'Producción y provisión del servicio'],
        ['codigo' => '8.6',   'titulo' => 'Liberación de los productos y servicios'],
        ['codigo' => '8.7',   'titulo' => 'Control de las salidas no conformes'],
        ['codigo' => '9.1',   'titulo' => 'Seguimiento, medición, análisis y evaluación'],
        ['codigo' => '9.2',   'titulo' => 'Auditoría interna'],
        ['codigo' => '9.3',   'titulo' => 'Revisión por la dirección'],
        ['codigo' => '10.1',  'titulo' => 'Generalidades (Mejora)'],
        ['codigo' => '10.2',  'titulo' => 'No conformidad y acción correctiva'],
        ['codigo' => '10.3',  'titulo' => 'Mejora continua'],
    ],

    /* ─── ISO 14001:2015 ────────────────────────────────────────────── */
    'ISO 14001' => [
        ['codigo' => '4.1',   'titulo' => 'Comprensión de la organización y su contexto'],
        ['codigo' => '4.2',   'titulo' => 'Comprensión de las necesidades y expectativas de las partes interesadas'],
        ['codigo' => '4.3',   'titulo' => 'Determinación del alcance del SGA'],
        ['codigo' => '4.4',   'titulo' => 'Sistema de gestión ambiental'],
        ['codigo' => '5.1',   'titulo' => 'Liderazgo y compromiso'],
        ['codigo' => '5.2',   'titulo' => 'Política ambiental'],
        ['codigo' => '5.3',   'titulo' => 'Roles, responsabilidades y autoridades en la organización'],
        ['codigo' => '6.1.1', 'titulo' => 'Generalidades – Acciones para abordar riesgos'],
        ['codigo' => '6.1.2', 'titulo' => 'Aspectos ambientales'],
        ['codigo' => '6.1.3', 'titulo' => 'Requisitos legales y otros requisitos'],
        ['codigo' => '6.1.4', 'titulo' => 'Planificación de acciones'],
        ['codigo' => '6.2',   'titulo' => 'Objetivos ambientales y planificación para lograrlos'],
        ['codigo' => '7.1',   'titulo' => 'Recursos'],
        ['codigo' => '7.2',   'titulo' => 'Competencia'],
        ['codigo' => '7.3',   'titulo' => 'Toma de conciencia'],
        ['codigo' => '7.4',   'titulo' => 'Comunicación'],
        ['codigo' => '7.5',   'titulo' => 'Información documentada'],
        ['codigo' => '8.1',   'titulo' => 'Planificación y control operacional'],
        ['codigo' => '8.2',   'titulo' => 'Preparación y respuesta ante emergencias'],
        ['codigo' => '9.1',   'titulo' => 'Seguimiento, medición, análisis y evaluación'],
        ['codigo' => '9.2',   'titulo' => 'Auditoría interna'],
        ['codigo' => '9.3',   'titulo' => 'Revisión por la dirección'],
        ['codigo' => '10.1',  'titulo' => 'Generalidades (Mejora)'],
        ['codigo' => '10.2',  'titulo' => 'No conformidad y acción correctiva'],
        ['codigo' => '10.3',  'titulo' => 'Mejora continua'],
    ],

    /* ─── ISO/IEC 27001:2022 ────────────────────────────────────────── */
    'ISO 27001' => [
        ['codigo' => '4.1',   'titulo' => 'Comprensión de la organización y su contexto'],
        ['codigo' => '4.2',   'titulo' => 'Comprensión de las necesidades y expectativas de las partes interesadas'],
        ['codigo' => '4.3',   'titulo' => 'Determinación del alcance del SGSI'],
        ['codigo' => '4.4',   'titulo' => 'Sistema de gestión de seguridad de la información'],
        ['codigo' => '5.1',   'titulo' => 'Liderazgo y compromiso'],
        ['codigo' => '5.2',   'titulo' => 'Política de seguridad de la información'],
        ['codigo' => '5.3',   'titulo' => 'Roles, responsabilidades y autoridades en la organización'],
        ['codigo' => '6.1.1', 'titulo' => 'Generalidades – Acciones para abordar riesgos'],
        ['codigo' => '6.1.2', 'titulo' => 'Evaluación de riesgos de seguridad de la información'],
        ['codigo' => '6.1.3', 'titulo' => 'Tratamiento de riesgos de seguridad de la información'],
        ['codigo' => '6.2',   'titulo' => 'Objetivos de seguridad de la información'],
        ['codigo' => '6.3',   'titulo' => 'Planificación de cambios'],
        ['codigo' => '7.1',   'titulo' => 'Recursos'],
        ['codigo' => '7.2',   'titulo' => 'Competencia'],
        ['codigo' => '7.3',   'titulo' => 'Toma de conciencia'],
        ['codigo' => '7.4',   'titulo' => 'Comunicación'],
        ['codigo' => '7.5',   'titulo' => 'Información documentada'],
        ['codigo' => '8.1',   'titulo' => 'Planificación y control operacional'],
        ['codigo' => '8.2',   'titulo' => 'Evaluación de riesgos de seguridad de la información'],
        ['codigo' => '8.3',   'titulo' => 'Tratamiento de riesgos de seguridad de la información'],
        ['codigo' => '9.1',   'titulo' => 'Seguimiento, medición, análisis y evaluación'],
        ['codigo' => '9.2',   'titulo' => 'Auditoría interna'],
        ['codigo' => '9.3',   'titulo' => 'Revisión por la dirección'],
        ['codigo' => '10.1',  'titulo' => 'Mejora continua'],
        ['codigo' => '10.2',  'titulo' => 'No conformidad y acción correctiva'],
    ],

];
